ALTER TABLE rob_ops     ADD COLUMN IF NOT EXISTS source VARCHAR(32) NULL;
ALTER TABLE sorcery_ops ADD COLUMN IF NOT EXISTS source VARCHAR(32) NULL;
ALTER TABLE attack_ops  ADD COLUMN IF NOT EXISTS source VARCHAR(32) NULL;
