export const BAD_SPELL_NAMES = [
  "Amnesia",
  "Chastity",
  "Expose Thieves",
  "Explosions",
  "Fireball",
  "Fool's Gold",
  "Greed",
  "Lightning Strike",
  "Meteor Showers",
  "Nightmares",
  "Pitfalls",
  "Storms",
  "Vermin",
] as const;
